astroufsc/chimera

- src/chimera/instruments/astelco.py
The telescope would lost connection after 2 minutes of inactivity. Also solves some minor issues. Specially from time to time there would occur some error with the connection to the telescope while slewing to an object causing chimera-tel, for instance, to crash. But, if you persist with the connection it would come back.
As requested, I checked out the latest version of chimera from astroufsc and uploaded the changes.
> Provides a fix for ticket #29

- README.md
First move to restructure the project's documentation.
> New documentation

- src/chimera/core/proxy.py
Fixes issue #39. Implemented function __setitem__ in core.proxy.Proxy.
> Fixes issue #39.

- src/scripts/chimera-filter
Fix #44  where chimera-filter would result in "invalid filter" no matter what.
> Fix issue #44.

- src/chimera/instruments/dome.py
- src/chimera/interfaces/dome.py
Subclass dome in order to separate the different properties of observatory domes. This is an intermediate commit aimed at providing support for fans and other optional attributes.
> Dome subclasses

- src/chimera/instruments/astelco.py
- src/chimera/instruments/telescope.py
- src/scripts/chimera-focus
- src/scripts/chimera-tel
This PR fixes the chimera-focus and chimera-tel bugs introduced by #33. I've rolled back the chimera-focus to pre-PR, changed the c_open and close to openCover() and likewise. I also fixed the cover help on chimera-tel.
> Fix chimera-focus and chimera-tel

- src/chimera/instruments/weatherstation.py
- src/chimera/interfaces/weatherstation.py
Fixed some typos and added a basic weatherstation instrument. Should be improved.
> Weather station interface update

- setup.py
This fixes windows installation errors.
> Removed pywin32 platform dependency

- src/chimera/instruments/faketelescope.py
> Added slew position validation to the fake telescope.

- src/chimera/util/image.py
This PR adds the FILENAME keyword to the images and fixes the comment of AUTHOR keyword to be precise with the standard dictionaries at http://fits.gsfc.nasa.gov/fits_dictionary.html
> Adds FILENAME keyword to the header. Fixes AUTHOR comment.

- src/chimera/core/manager.py
- src/chimera/core/remoteobject.py
- src/chimera/core/tests/test_location.py
- src/chimera/instruments/fakecamera.py
> Changed all `== None` by `is None`. Fixes #98.

- src/chimera/controllers/autofocus.py
- src/chimera/util/ds9.py
- src/scripts/chimera-focus
This is the version being used on T80S and LNA for having the camera on a Windows machine and the Autofocus (which needs sextractor) on a remote linux machine.
> Autofocus remote

- src/chimera/controllers/scheduler/handlers.py
> Removed opeSlit from scheduler point handler for safety

- src/chimera/core/site.py
> Fix issue #109 site's SunPos, MoonPos and others

- src/chimera/instruments/faketelescope.py
- src/chimera/instruments/telescope.py
- src/chimera/interfaces/telescope.py
- src/scripts/chimera-tel
* Now both Telescope Cover and Pier Side uses features on chimera-tel
* Removed TelescopeCover Telescope instrument inheritance
* Removed silly /dev/ttyS0 Telescope default device
> Re-worked Pier Side and Telescope Cover

- docs/site/advanced.rst
- src/chimera/core/systemconfig.py
- src/chimera/instruments/calibrationlamp.py
- src/chimera/instruments/fakecalibrationlamp.py
- src/chimera/interfaces/calibrationlamp.py
- src/scripts/chimera-dome
**MINOR PR**
* Fixed documentation;
* Fixed prints on CalibrationLamps;
* Now using `features` to check if lamp supports dimming or not;
* Now prints dimming status on chimera-dome;
> Calibrationlamps update

- src/scripts/chimera-dome
Just to fix a typo introduced on #123.
> Fix silly bug introduced on 123

- src/scripts/chimera-sched
Replace PR #147 which was based on a developer branch. 
Implement the ability  to configure the scheduler database using a yaml file. This adds much more freedom to configure the scheduler.
> Implement yaml configuration to the scheduler database.

- src/chimera/controllers/scheduler/executor.py
- src/chimera/controllers/scheduler/handlers.py
- src/chimera/controllers/scheduler/model.py
- src/chimera/interfaces/autoflat.py
Adds auto flat interface and scheduler action.
> Scheduler auto flat

- src/chimera/controllers/imageserver/imagerequest.py
- src/scripts/chimera-cam
This PR fixes `chimera-cam` when the dome is not on the same host of the camera.
> Fix chimera cam dome

- src/chimera/controllers/scheduler/controller.py
- src/scripts/chimera-sched
Fixes some issues that where introduced when creating the PR merge for the yaml scheduler configuration and the Autoflat.
> Scheduler bug fixes.

- src/chimera/controllers/scheduler/handlers.py
- src/chimera/controllers/scheduler/model.py
- src/scripts/chimera-sched
This PR adds --compress to chimera-sched command line options for image compression
> Add chimera-sched --compress option

- src/chimera/controllers/scheduler/handlers.py
- src/chimera/controllers/scheduler/model.py
- src/scripts/chimera-sched
This enables the user to configure telescope offsets (North/South - East/West) in the scheduler, useful to configure dithering patterns for instance.
> Implements telescope offsets in scheduler.

- src/chimera/instruments/camera.py
- Added two keywords to specify the lower left corner of the subframe.
These coordinates are taken directly from imageRequest['window'].
Fixes #162
> Added subframe keywords to image header

- src/chimera/instruments/camera.py
Adds the CCDSUM keyword for the binning of images following the same standard of #163.
> Add CCDSUM keyword for the binning of images

- src/chimera/instruments/camera.py
> CCDSUM fix

- src/chimera/controllers/scheduler/handlers.py
- src/chimera/instruments/camera.py
> Add filter to autofocus handler of scheduler

- src/chimera/instruments/fakefocuser.py
- src/chimera/util/findplugins.py
- src/scripts/chimera-focus
Fix plugins loading and chimera-focus. Adds temperature information to the fake focuser.
> Fix plugin loading and chimera-focus
