src/chimera/util/image.py
It is important to increase the precision of the timestamp on the header when observing fast transits of objects like TNOs.
=> [chimera-cam] Print microseconds to DATE-OBS fits file header keyword.

src/chimera/instruments/astelcodome.py
Add move to azimuth, to move the dome when in stand mode. It also fixes indentation to comply with PEP8.
=> Minor improvements on AstelcoDome. 

src/chimera/controllers/imageserver/util.py, src/chimera/controllers/site/main.py, src/chimera/core/cli.py, src/chimera/core/path.py, src/chimera/util/findplugins.py, src/scripts/chimera-admin
Makes chimera look for instruments and controllers in all python modules which name starts with ``chimera_``. A template example can be found on the link below. Fixes #56.
https://github.com/astroufsc/chimera_template
=> Chimera plugins

src/chimera/controllers/autofocus.py, src/chimera/instruments/camera.py, src/chimera/interfaces/camera.py, src/chimera/interfaces/filterwheel.py, src/chimera/util/image.py
This PR changes two things that are correlated:
1) It fixes few fits keywords to the standard keywords defined on http://heasarc.gsfc.nasa.gov/docs/fcg/standard_dict.html. The header keywords which were renamed are: CAMERA to INSTRUME and CREATOR to AUTHOR
2) Changes the defaults of configuration parameters that are strings to "Unknown" and removes the default for `telescope_focal_length` and `ccd_saturation_level` which could lead to a wrong WCS on the image file or problems on doing autofocus.
=> Camera fits headers and config adjustments

src/chimera/instruments/focuser.py
This PR simply adds the focuser temperature information to the image headers via the getMetadata() method on instruments.focuser.
=> Add focus temperature to the image headers

src/chimera/instruments/camera.py, src/chimera/interfaces/camera.py
Definition of the rotation matrix is found here: http://www.astro.iag.usp.br/~moser/notes/GAi_FITSimgs.html.
=> Add the ability to include camera rotation to the image WCS. 

src/chimera/controllers/imageserver/imageserverhttp.py
This PR provides a fix for issue #94 where, in some platforms, opening the fits file for reading only would cause problems with the image transfer, apparently due to the interpretation of EOL and EOF. Opening the file for reading in binary mode fix this issue.
=> Fix issue 94

src/chimera/interfaces/autoguider.py
Replaced guiderStopped by guiderStop in order to retain compatibility with guiderStart action. Added "nlost" to configuration, the number of times guider will keep trying to guide before giving up when star is lost (for poor weather, for instance).
=> Minor changes to autoguider interface. 

src/chimera/controllers/imageserver/imagerequest.py, src/chimera/instruments/camera.py, src/chimera/util/image.py, src/scripts/chimera-cam
After astroufsc/chimera#40 some controllers started to not work because of the lack of the  `.fits` file. This is due two reasons:
* The default `ImageRequest` compress parameters are defined to be `True` and `bz2`,  compressing images always by default.
* On the camera instrument, it always compress the files using bzip2, no matter if `compress` is set to `False` or `compress_format` is not `bz2` on the `ImageRequest`.
This PR fixes this behavior by adding sane defaults and fixing camera instrument.
=> Fixes image saving behaviour

src/chimera/interfaces/autoguider.py
Realized that the autoguider actually needs to know about the scheduler. This is required, for example, to answer events such as an abort sequence.
=> Adds scheduler instance to autoguider basic configuration.

src/chimera/instruments/faketelescope.py, src/chimera/interfaces/telescope.py
Updated FakeTelescope to use the new signaling events. Also, on FakeTelescope, added a ``startTracking`` after a ``slewToRaDec`` operation. 
All other external telescope drivers should be updated to include this.
This is actually a major requirement for various reasons, including safety. For instance, rigth now chimera is not aware in case the telescope reaches a low altitute limit as well as if there is any other problem which stops tracking.
=> Add event to signal that telescope started/stopped tracking. 

src/chimera/instruments/dome.py, src/chimera/instruments/fakedome.py, src/chimera/interfaces/dome.py, src/scripts/chimera-dome
Updated interface, instrument and fakedome. 
On chimera-dome, show information about flap status, change ``open`` and ``close`` functions to ``openSlit`` and ``closeSlit`` and added ``openFlap`` and ``closeFlap``. Note that this does not drop backward capabilities. It only changes the key on the chimera script, not the drivers.
When showing information about flap status, capture ``NotImplementedError`` because a considerable number of domes don't have flaps.
=> Add dome flap to dome. 

src/chimera/instruments/telescope.py, src/chimera/interfaces/telescope.py, src/scripts/chimera-tel
* Added missing isCoverOpen() method
* Added telescope cover methods to the interface. They were only on the instrument
* If there is a isCoverOpen() method, `chimera-tel --info` will tell about it
=> Telescope cover minor fixes

src/chimera/core/manager.py, src/chimera/core/systemconfig.py
This PR fixes #100 by changing the host to `None` when the `host: 0.0.0.0` is set on the `chimera` sction of the configuration file.
=> Listen on ALL interfaces when host is 0.0.0.0

src/chimera/core/chimeraobject.py, src/chimera/core/tests/test_chimera_object.py
As discussed on #124, I introduce a `features` method on `ChimeraObject` to check if the object is an instance of another object. That way, one can check if an instrument supports a part of the interface or not by doing, for example:
```python
from chimera.core.manager import Manager
from chimera.interfaces.dome import DomeFlap, DomeLights
m = Manager()
dome = m.getProxy('127.0.0.1:7666/Dome/0')
print 'Flap', dome.features(DomeFlap)
print 'Lights', dome.features(DomeLights)
```
=> Adds `features` method to check if an instrument or controller features an interface or not

src/chimera/core/chimera.sample.config, src/chimera/core/systemconfig.py, src/chimera/instruments/calibrationlamp.py, src/chimera/instruments/dome.py, src/chimera/instruments/fakecalibrationlamp.py, src/chimera/interfaces/calibrationlamp.py, src/chimera/interfaces/dome.py, src/scripts/chimera-dome
As suggested on issue #83. 
* Removed all references to ``domelights``.
* Added interface, base instrument and fake instrument.
* Modified chimera-dome script for the new usage. It is possible to work with more than one lamp easily. When info is issued it will show the status of each lamp (or nothing, if none is present).
To configure a single lamp:
```
calibrationlamp:
- name: fake
type: FakeCalibrationLamp
dome_az: 0
telescope_alt: 90
telescope_az: 45
```
On `chimera-dome --info`:
```
======================================== 
Dome: /FakeDome/fake (/dev/ttyS1). 
Current dome azimuth: 42.13. 
Current dome mode: None. 
Dome slit is closed. 
======================================== 
Lamp /FakeCalibrationLamp/fake: OFF 
======================================== 
```
Or a series of lamps:
``` …
```
=> Introduces the ``calibrationlamp`` instrument. 

src/chimera/instruments/fakecamera.py, src/chimera/instruments/faketelescope.py, src/chimera/instruments/telescope.py
The epoch on the image headers is set hardcoded to be 2000. Changed the `faketelescope` to be able to test different coordinates.
=> Fix epoch on header

src/chimera/controllers/scheduler/model.py, src/scripts/chimera-sched
This PR fixes #104 by adding a `-o` option to the `chimera-sched` script like the one on `chimera-cam`:
```
$ chimera-sched --help
...
-o OUTPUT, --output=OUTPUT
Images base filename including full path if needed.
[default=$NAME-$DATE-$TIME]
...
``
=> Adds scheduler image output filename option. Fixes #104

setup.py, src/chimera/instruments/fakeweatherstation.py, src/chimera/instruments/seeingmonitor.py, src/chimera/instruments/weatherstation.py, src/chimera/interfaces/seeingmonitor.py, src/chimera/interfaces/weatherstation.py, src/scripts/chimera-focus, src/scripts/chimera-seeing, src/scripts/chimera-weather
This PR introduces `chimera-weather` and `chimera-seeing` scripts. Also, it standardizes the `SeeingMonitor` interface which was very different from the weather station notation.
Sample output of the scripts below. Red color means that the information is too old.
=> chimera-weather and chimera-seeing scripts

src/chimera/instruments/fakeweatherstation.py, src/chimera/instruments/weatherstation.py, src/chimera/interfaces/weatherstation.py, src/scripts/chimera-seeing, src/scripts/chimera-weather
This PR changes the interface of the Weather Station to:
* Divide the Weather station features in WeatherTemperature, WeatherHumidity, WeatherRain, and so on... This is useful to use the `features` method added on #134.
* Add new types of weather information: `Sky Transparency` to be used with instruments such as RASICAM and AAG Cloud Watcher and `WeatherSafety` which is mean to be used with some instruments that are able only tell that is okay to observe or not.
=> Weather station interface review

src/chimera/util/image.py, src/scripts/chimera-cam
Adds RICE_ONE FITS standard compression option for chimera. To use it:
``chimera-cam -t NNN --compress fits_rice``
For more info on compressed fits files:
http://docs.astropy.org/en/stable/io/fits/usage/unfamiliar.html
https://heasarc.gsfc.nasa.gov/fitsio/fpack/
=> Add rice compression

src/chimera/util/image.py
This PR fixes few bugs introduced on PR #144. Bugs where:
* Images were being returned without header
* On newer versions of astropy, an exposure returns an Exception due to existing file.
=> Fix camera bugs

src/chimera/controllers/imageserver/imageserver.py, src/scripts/chimera-cam
Fixes a memory leak on chimera that allows imageserver to open an unrestricted number of fits files (#164). The user can control the number of images added to the queue (default=10) in the configuration file. Control is done when registering images. This also fixes the “Too many open files” issue, #160 and #37, without the need to track all calls to camera.expose().
=> Fix issues #164, #160 and #37.

src/chimera/instruments/camera.py, src/chimera/instruments/tests/test_camera.py
In compressed images, two `DATE-OBS` keywords were being saved. Only the HDU0 keyword was correct. This PR fixes this problem and moves to HDU1 these keywords when a compressed file is asked.
This also adds a test for `fz` compressed files on camera.
=> Fix headers

setup.py
The newer versions ``astropy`` only support Python 3. 
I inserted a restriction on ``setup.py`` to use the Python 2 compatible versions.
In Portuguese:
>  astropy agora (a partir da versão 3) só é compatível com python 3. 
Como estou aprendendo a usar o github, fiz uma atualização no ``setup.py``por aqui.
=> astropy for py2
